### ISSUE TITLE
Move Janus stellar flux management functions into Mors

### ISSUE THREAD

**Issue by lsoucasse** [FormingWorlds/MORS#11]
It makes more sense to have the stellar spectrum utils functions of Janus into Mors, i.e.:
- the StellarSpectrum module (InsertStellarSpectrum, PrepareStellarSpectrum)
- the ReadSpectralFile module (ReadBandEdges function) --> to be confirmed?

**Comment by nichollsh** [comment]
I think that `ReadBandEdges`, `PrepareStellarSpectrum`, and `InsertStellarSpectrum` should stay inside JANUS because they directly concern SOCRATES spectral files. The latter two are of course related to the stellar spectrum, but don't have any utility outside the context of SOCRATES.

**Comment by lsoucasse** [comment]
OK. I am closing this issue then.
