### ISSUE TITLE
Age not defined when using Spada tracks (Python 3.13)

### ISSUE THREAD

**Issue by nichollsh** [FormingWorlds/MORS#25]
When running PROTEUS with MORS (Spada) the model crashes on initialisation.

This is the error:
```python
  File "/home/n/nichollsh/PROTEUS/src/proteus/cli.py", line 75, in start
    runner.start(resume=resume)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/n/nichollsh/PROTEUS/src/proteus/proteus.py", line 242, in start
    init_star(self)
    ~~~~~~~~~^^^^^^
  File "/home/n/nichollsh/PROTEUS/src/proteus/star/wrapper.py", line 46, in init_star
    handler.stellar_track = mors.Star(Mstar = handler.config.star.mass,
                            ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                      percentile = handler.config.star.mors.rot_pctle)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/n/nichollsh/MORS/src/mors/star.py", line 101, in __init__
    self._LoadEvoTracks(Age,OmegaEnv,OmegaCore,AgesOut=AgesOut)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/n/nichollsh/MORS/src/mors/star.py", line 168, in _LoadEvoTracks
    self._setupQuantityFunctions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/n/nichollsh/MORS/src/mors/star.py", line 187, in _setupQuantityFunctions
    exec( "setattr( self.__class__ , '"+track+"' , "+track+" )" )
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'Age' is not defined
```

PROTEUS configuration file attached: [trappist1b.txt](https://github.com/user-attachments/files/17520728/trappist1b.txt)

@lsoucasse any ideas? Have you seen this before? I assume you left the comments regarding this strange `exec()` implementation - I agree with these. However, maybe the fix here is simply to pass `Age` into this `_setupQuantityFunctions()` function.

**Comment by lsoucasse** [comment]
I really do not understand this error. You don't need the star age to create the star object (this is the whole point of creating the track over time and then access it with the Value function for a given time).

Independently of proteus, the command `star = mors.Star(Mstar=0.1, percentile=50)` (which corresponds to the input) runs fine for me.

**Comment by nichollsh** [comment]
I find it strange too. The line before the one throwing the error also uses an `exec()` call, which makes reference to a variable called `Age`. Maybe it's actually coming from that instead?

```python
exec( "def "+track+"(self,Age):\n  return self.Value(Age=Age,Quantity='"+track+"')" )
```

**Comment by lsoucasse** [comment]
Also managed to run proteus with current main branch and your input file. It does not crash.

It does not seem related but have you updated your mors version?

**Comment by nichollsh** [comment]
I get the same error when running the tests locally too: `pytest` shows that the Baraffe tracks run fine but the Spada ones fail. Python 3.13 and MORS commit 8bc386dc96ae78a0484890951a17db98aa8ac8b2

```python
tests/test_spada.py:16: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
src/mors/star.py:101: in __init__
    self._LoadEvoTracks(Age,OmegaEnv,OmegaCore,AgesOut=AgesOut)
src/mors/star.py:168: in _LoadEvoTracks
    self._setupQuantityFunctions()
src/mors/star.py:187: in _setupQuantityFunctions
    exec( "setattr( self.__class__ , '"+track+"' , "+track+" )" )
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   NameError: name 'Age' is not defined

<string>:1: NameError
===================================== short test summary info ======================================
FAILED tests/test_spada.py::test_spada[inp0-expected0] - NameError: name 'Age' is not defined
FAILED tests/test_spada.py::test_spada[inp1-expected1] - NameError: name 'Age' is not defined
FAILED tests/test_spada.py::test_spada[inp2-expected2] - NameError: name 'Age' is not defined
FAILED tests/test_spada.py::test_spada[inp3-expected3] - NameError: name 'Age' is not defined
============================= 4 failed, 2 passed in 512.22s (0:08:32) ==============================
```

**Comment by nichollsh** [comment]
The test seems to pass fine on Python 3.12, so I guess that's why this issue seems to have come about seemingly spontaneously. Maybe there's something strange with the way the `exec()` calls interact with the new version of Python, so we should probably think about reworking them.

**Comment by nichollsh** [comment]
I assume this is related to this change: https://docs.python.org/3.13/whatsnew/3.13.html#changes-in-the-python-api

> Code execution functions that implicitly target locals() (such as exec and eval) must be passed an explicit namespace to access their results in an optimized scope. (Changed as part of [PEP 667](https://peps.python.org/pep-0667/).)

> Calling [locals()](https://docs.python.org/3.13/library/functions.html#locals) from a comprehension at module or class scope (including via exec or eval) once more behaves as if the comprehension were running as an independent nested function (i.e. the local variables from the containing scope are not included
